version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0-jammy
    container_name: yubyuyi-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: yubyuyi
    networks:
      - yubyuyi-network

  # Backend API (Node.js/Express)
  backend:
    build:
      context: ./tan
      dockerfile: Dockerfile
    container_name: yubyuyi-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - mongodb
    networks:
      - yubyuyi-network
    volumes:
      - ./tan/logs:/app/logs

  # Frontend (Next.js)
  frontend:
    build:
      context: ./mark
      dockerfile: Dockerfile
    container_name: yubyuyi-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 8000
      FRONTEND_URL: localhost:3000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/yubyuyi?authSource=admin
      ACCESS_SECRET: TRALALELOTRALALA
      ACCESS_EXPIRE: 7d
      REFRESH_SECRET: BOMBARDINOCROCODILO
      REFRESH_EXPIRE: 7d
      PROJECT_NAME: YubYuYi  
    depends_on:
      - backend
    networks:
      - yubyuyi-network

networks:
  yubyuyi-network:
    driver: bridge